version: "3"
services:
  mobile-payment-backend:
    image: ravindula/mobile-payment-backend-image
    restart: always
    build: .
    networks:
      - spring-net3
    ports:
      - 8085-8095:8080
    environment:
      MYSQL_HOST: abc-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    # container_name: card-payment-backend

  abc-mysql2:
    container_name: abc-mysql2
    image: mysql
    networks:
      - spring-net3
    ports:
    - 3308:3306
    environment:
      MYSQL_DATABASE: tls_db
      MYSQL_ROOT_PASSWORD: root


networks:
  spring-net3:
    name: spring-net3
    driver: spring-net3